---
- name: create instances developer&production on AWS
  hosts: all
  become: yes
  
  tasks:
    - ec2:
        key_name: aws_key
        region: us-east-2
        instance_type: t2.micro
        image: ami-0742a572c2ce45ebf
        wait: yes
        vpc_subnet_id: subnet-29e63245
        assign_public_ip: yes
        instance_tags:
          tpinst: developer
        gather_facts: True  
        state: present



- name: create instances developer&production on AWS


    - ec2:
          key_name: aws_key
          region: us-east-2
          instance_type: t2.micro
          image: ami-0742a572c2ce45ebf
          wait: yes
          vpc_subnet_id: subnet-29e63245
          assign_public_ip: yes
          instance_tags:
            tpinst: production 
          state: present   

- name: GetInstanses IP
  - ec2_instance_facts:
     region: us-east-2
     filters:
        "tag:tpinst": developer 
    register: ec2_metadata    

- name: Ensure all need PO
  hosts: all
  become: yes

    apt: {{ item }} state=present
    with_items:
       - default-jdk
       - git
       - python
       - python-pip

    command: pip install boto   

- name: Provisioning developers pc
  hosts: Developers
  become: yes

  tasks:
  - name: Ensure maven is present
    apt:
     name: maven
     state: present
 
  - name: deploy git project boxfuse
    git:  
     repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
     dest: /home/user/boxfuse
     force: yes
     clone: yes

  - name: create artefact boxfuse
    command: mvn package
    args:
     chdir: /home/user/boxfuse/

  - name: copy artefact to folder my repository
    copy:
      src: /home/user/boxfuse/target/hello-1.0.war
      dest: /home/gendalf/boxfuseartefact/

  - name: deploy artefact to my git repository
    git:
      repo: https://github.com/GendalfGV/boxfuseart.git
      version: master
      update: yes    

- name: Provisioning production
hosts: production
become: yes

  tasks:
  - name: Ensure  Tomcat9 is present
    apt:
      name: tomcat9
      state: present

  - name: deploy git project myboxfuse artefact
    git:  
      repo: 'https://github.com/GendalfGV/StudyDevOps.git'
      dest: /home/user/myboxfuseartefact/
      force: yes
      clone: yes 

  - name: copy artefact to tomcat9
     copy:
       src: /home/user/myboxfuseartefact/hello-1.0.war
       dest: /var/lib/tomcat9/webapps/

   
